#ifndef BOARD_H_
#define BOARD_H_




#define USART3_RX_DMA_INDEX  0U
#define USART3_TX_DMA_INDEX  1U

#define USART3_TX_GPIO_INDEX 0U
#define USART3_RX_GPIO_INDEX 1U

#define BNO055_I2C_SDA_GPIO_INDEX 2U
#define BNO055_I2C_SCL_GPIO_INDEX 3U

#define BNO055_INT_GPIO_INDEX 4U
#define BNO055_INT_Pin GPIO_PIN_13
#define BNO055_INT_GPIO_Port GPIOC
#define BNO055_INT_GPIO_EXTI_IRQn EXTI15_10_IRQn

#define BUTTON_GPIO_INDEX 4
#define BUTTON_GPIO_Pin GPIO_PIN_13
#define BUTTON_GPIO_GPIO_Port GPIOC
#define BUTTON_GPIO_EXTI_IRQn EXTI15_10_IRQn

#define LED_GREEN_GPIO_INDEX 5
#define LED_GREEN_Pin GPIO_PIN_0
#define LED_GREEN_GPIO_Port GPIOB

#define LED_RED_INDEX 6
#define LED_RED_Pin GPIO_PIN_14
#define LED_RED_GPIO_Port GPIOB
#define LED_RED_PWM_INDEX 0U
#define LED_RED_PWM_INSTANCE TIM12
#define LED_RED_PWM_CHANNEL TIM_CHANNEL_1
#define LED_RED_PWM_GPIO_AF GPIO_AF9_TIM12
#define LED_RED_PWM_DUTY_MAX 255U

#define MOTOR1_GPIO_INDEX 8U
#define MOTOR1_Pin GPIO_PIN_5
#define MOTOR1_GPIO_Port GPIOA
#define MOTOR1_INDEX 0U
#define MOTOR1_TYPE DRV_MOTOR_TYPE_POSITION_SERVO
#define MOTOR1_PWM_INDEX 1U
#define MOTOR1_PWM_INSTANCE TIM2
#define MOTOR1_PWM_CHANNEL TIM_CHANNEL_1
#define MOTOR1_PWM_GPIO_AF GPIO_AF1_TIM2
#define MOTOR1_SERVO_MIN_PULSE_US 500U
#define MOTOR1_SERVO_CENTER_PULSE_US 1500U
#define MOTOR1_SERVO_MAX_PULSE_US 2500U
#define MOTOR1_SERVO_MAX_ANGLE_DEG 180.0f

#define MOTOR2_GPIO_INDEX 9U
#define MOTOR2_Pin GPIO_PIN_6
#define MOTOR2_GPIO_Port GPIOA
#define MOTOR2_INDEX 1U
#define MOTOR2_TYPE DRV_MOTOR_TYPE_POSITION_SERVO
#define MOTOR2_PWM_INDEX 2U
#define MOTOR2_PWM_INSTANCE TIM3
#define MOTOR2_PWM_CHANNEL TIM_CHANNEL_1
#define MOTOR2_PWM_GPIO_AF GPIO_AF2_TIM3
#define MOTOR2_SERVO_MIN_PULSE_US 500U
#define MOTOR2_SERVO_CENTER_PULSE_US 1500U
#define MOTOR2_SERVO_MAX_PULSE_US 2500U
#define MOTOR2_SERVO_MAX_ANGLE_DEG 180.0f

#define MOTOR_SERVO_DUTY_MAX 255U
#define MOTOR_SERVO_PWM_FREQUENCY_HZ 50U
#define MOTOR_SERVO_SPEED_MAX 1000

#define LED_BLUE_INDEX 7
#define LED_BLUE_Pin GPIO_PIN_7
#define LED_BLUE_GPIO_Port GPIOB


#endif
